name: Integration Tests with MySQL

env:
    MYSQL_DATABASE: ${{ secrets.DB_NAME }}
    DB_USER: ${{ secrets.DB_USER }}
    DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
    
on:
  pull_request:
    branches: [main]

jobs:
  integration_tests_mysql:
    runs-on: ubuntu-latest

    steps:

    - name: Start MySQL
      run: sudo /etc/init.d/mysql start
      

    - name: Create Database
      run: mysql --port 3306 -u ${{secrets.DB_USER}} -p${{secrets.DB_PASSWORD}} 
      env:
        MYSQL_DATABASE: ${{secrets.DB_NAME}}

    - name: Checkout Repository
      uses: actions/checkout@v2
    
    # - name: Debug Check Variables
    #   run: mysql -h 127.0.0.1 --port 3306 -u ${{secrets.DB_USERNAME}} -p${{secrets.DB_PASSWORD}}
 
    - name: Debug Environment Variables
      run: echo "DB_HOST=${{ secrets.DB_HOST }} DB_USER=${{ secrets.DB_USER }} DB_PASSWORD=${{ secrets.DB_PASSWORD }} DB_NAME=${{ secrets.DB_NAME }}"
    
    - name: Install Dependencies
      run: npm ci

    # - name: Check MySQL Status
    #   run: echo "SHOW STATUS LIKE 'Uptime';" | mysql -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} -h${{ env.DB_HOST }} -P3306 ${{ secrets.DB_NAME }}

    - name: Run Integration Tests
      run: npm test

