name: Packer Continuous Integration

on:
    pull_request:
      branches: [main]

jobs:
  packer-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Packer
        uses: hashicorp/setup-packer@main
        with:
            version: 1.10.1

      - name: cd to packer directory
        run:  cd packertest

      - name: checking diret
        run:  ls -la

      - name: Format Packer Template
        run: packer fmt packertest/example.pkr.hcl

      - name: Validate Packer Template
        run: packer validate packertest/example.pkr.hcl
