name: Packer Continuous Integration

on:
    pull_request:
      branches: [main]

jobs:
  packer-ci:
    runs-on: ubuntu-latest

    env:
        GCP_COMPUTE: ${{ secrets.GCP_COMPUTE }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Packer
        uses: hashicorp/setup-packer@main
        with:
            version: 1.10.1

      - name: Zip Packer Artifacts
        run: zip -r webapp-main.zip ./*

      - name: checking diret
        run:  ls -la

      - name: Init Packer Template
        run: packer init packertest/example.pkr.hcl

      - name: Format Packer Template
        run: packer fmt packertest/example.pkr.hcl

      - name: Validate Packer Template
        run: packer validate packertest/example.pkr.hcl
